### ISSUE TITLE
第四种样式, 如果手动滚动的位置会错乱

### ISSUE THREAD

**Issue by JasonSparrow** [MQZHot/ZCycleView#11]
![simulator screen shot - iphone x - 2018-07-16 at 09 34 19](https://user-images.githubusercontent.com/15692322/42740541-7b4cdd84-88db-11e8-8b69-29ba98f0f0fa.png)
应该是contentOffset 引起的

**Comment by MQZHot** [comment]
注释掉 collectionView.isPagingEnabled = true 就可以了
