### ISSUE TITLE
可否放宽 Kingfisher 的版本要求？

### ISSUE THREAD

**Issue by PleaseDont** [MQZHot/ZCycleView#5]
可不可以把

`s.dependency 'Kingfisher', '~> 4.3.1'`

改为

`s.dependency 'Kingfisher', '>= 4.3.1'`

**Comment by MQZHot** [comment]
今天也注意到版本过低了😆

**Comment by PleaseDont** [comment]
@MQZHot 谢谢，very nice 😄
